# Generated by Django 5.1 on 2024-08-15 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custermer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custermer_titlename', models.CharField(max_length=100)),
                ('Custermer_name', models.CharField(max_length=100)),
                ('Custermer_nickname', models.CharField(max_length=100)),
                ('Custermer_phone', models.CharField(max_length=10)),
                ('Custermer_email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custermer_province', models.CharField(max_length=100)),
                ('Custermer_district', models.CharField(max_length=100)),
                ('Custermer_canton', models.CharField(max_length=100)),
                ('Custermer_postalnumber', models.CharField(max_length=10)),
                ('Custermer_housenumber', models.CharField(max_length=10)),
                ('Custermer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custerapp.custermer')),
            ],
        ),
    ]
