# Generated by Django 3.2 on 2024-09-11 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_title_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_nickname', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('customer_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_province', models.CharField(max_length=100)),
                ('customer_district', models.CharField(max_length=100)),
                ('customer_canton', models.CharField(max_length=100)),
                ('customer_postal_number', models.CharField(max_length=10)),
                ('customer_house_number', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custerapp.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_location',
            name='Custermer_id',
        ),
        migrations.DeleteModel(
            name='Custermer',
        ),
        migrations.DeleteModel(
            name='Customer_location',
        ),
    ]
